### ISSUE TITLE
程序测试问题集锦_v0

### ISSUE THREAD

**Issue by yanpingWu** [yujianke100/Sub-Bipartite-Graph-Creator#2]
1. 初始化运行的时候，主界面一直显示不出来
2. 主界面上有几个细节：类似"Node#"、”Edge#“不够规范
3. 主界面建议添加取消全选的按钮，毕竟选择的数据集多

**Comment by yujianke100** [comment]
1.没给终端挂梯子。挂了会自动下载所需的浏览器，然后就能打开了。
2.改了姐姐
3.嗻
